Ui/Controllers/CalendarioController.cs
using System.Net.Mail;
using Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository;
using System.Data;
using System.Linq;
using System.Security.Claims;
using DocumentFormat.OpenXml.InkML;
using Newtonsoft.Json;

namespace Ui.Controllers
{
   [Authorize]
    public class CalendarioController : Controller
    {

        private IEnumerable<PacienteObj> opc;


        private readonly IEventos  _IEventos;
       
        private readonly IPaciente _Paciente;
        public CalendarioController(IEventos eventos, IPaciente paciente)
        {
            _IEventos = eventos; //Inyeccion de dependencias
            _Paciente = paciente; //Inyeccion de dependencias

        }


        [Produces("application/json")]
        public IActionResult SearchUser(string term = null)
        {
           var Data = _Paciente.ObtenerPacienteCalendario();


           var result = Data
                .Where(u => u.nombreCompleto.ToLower().Contains(term.ToLower()))
                .ToList();
            return Json(result);
        }

        public IActionResult IndexPrueba()
        {

            return View();
        }


        [HttpGet]
        public IActionResult Index1()
        {
            ClaimsPrincipal currentUser = User;
            var identityl = (System.Security.Claims.ClaimsIdentity)User.Identity;
            string idf = identityl.Claims.FirstOrDefault(c => c.Type == "id").Value;


            var events = _IEventos.ObtenerEventoIdPaciente(idf);


            return View(events);

        }

            [HttpGet]
            public IActionResult GetCalendarEvents(string start, string end)
            {
                var events = _IEventos.ObtenerListaEventos();

            return Json(events);
            }

        //Agregar Eventos

            [HttpPost]
            public IActionResult AddEvent([FromBody] EventosObj data)


            {
                string message = String.Empty;
            EmailObj em = new EmailObj();
            if(em.correo == null | em.correo =="") {

                string mail = HttpContext.Session.GetString("Correo");
                em.correo = mail;
            }
            else { em.correo = data.correo; }
               

          

            _IEventos.InsertarEvento(data);
            sendEmail(data.start, data.end,em);


            return Json(new { message });
            }

        
        //Elimina Eventos
        [HttpPost]
            public IActionResult DeleteEvent([FromBody] Event evt)
            {
            string message = String.Empty;

            var events = _IEventos.ObtenerEventoId(evt.EventId);
            if (events != null)
            {
                
                _IEventos.EliminarEvento(evt.EventId);

            }

            return Json(new { message });
            }



        //Obtiene los Eventos
        public JsonResult GetEvents()
        {

            var events = _IEventos.ObtenerListaEventos();


            
            if (User.IsInRole("2"))
            {
                //events.ToList().ForEach(c => c.display = "background");
                events.ToList().ForEach(c => c.title = "");

            }


            return Json(events);
        }


        //Obtienen Paciente 
        public JsonResult GetPatient(string evt)
        {

            var Data = _Paciente.ObtenerPacienteCalendario();

            evt = "Eduardo";



            var re = (from faru in Data where faru.nombreCompleto.Contains(evt) select faru).FirstOrDefault();


            return Json(re);
        }




        [Produces("application/json")]
        public IActionResult SearchPatient(string term)
        {
            var Data = _Paciente.ObtenerPacienteCalendario();


            var result = (from faru in Data where faru.nombreCompleto.Contains(term) select faru).FirstOrDefault();
            return Json(result);
        }




        [HttpGet]
        public JsonResult SearchPatient1(int id)
        {

            var Data = _Paciente.ObtenerPacienteId(id);
            Data.nombreCompleto = Data.nombrePaciente + " " + Data.apellido1Paciente + " " + Data.apellido2Paciente;


            //var result = (from faru in Data where faru.nombreCompleto.Contains(id.ToString()) select faru).FirstOrDefault();
            return Json(Data);
          
        }





        public void sendEmail(DateTime start, DateTime end, EmailObj email)
        {

            SmtpClient smtp = new SmtpClient("smtp.office365.com");

            smtp.Port = 587;
            smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
            smtp.UseDefaultCredentials = false;
            System.Net.NetworkCredential credential =
                new System.Net.NetworkCredential("notificaciones@torresdent.com", "3teshe-ZY");
            smtp.EnableSsl = true;
            smtp.Credentials = credential;

            MailMessage mensaje = new MailMessage("notificaciones@torresdent.com", email.correo);
            mensaje.Subject = "Nueva cita agendada - Clínica Dr Torres";
            mensaje.Body = String.Format("<p>Estimado paciente,</p>\n<p>Se ha agendado una nueva cita:</p>\n<p>Inicio: {0}</p>\n<p>Finalización: {1}</p>\n<p>En el siguiente enlace podr&aacute; ingresar a la p&aacute;gina web: <a title=\"Cl&iacute;nica Dr Torres\" href=\"https://www.torresdent.com/login/index\" target=\"_blank\">Cl&iacute;nica Dr Torres</a></p>", start, end);
            mensaje.IsBodyHtml = true;
            smtp.Send(mensaje);

        }




    }




}



    

Ui/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Repository;
using Entities;
using System.Data;
// AUTHENTICATION COOKIE
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using DocumentFormat.OpenXml.Bibliography;
using DocumentFormat.OpenXml.Spreadsheet;
using PaulMiami.AspNetCore.Mvc.Recaptcha;

namespace Ui.Controllers
{
    [Route("login")]
    public class LoginController : Controller
    {
        private readonly ILogin _iLogin;
        private readonly IBitacora _ibitacora;
        public LoginController(ILogin iLogin, IBitacora Ibitacora)
        {
            _iLogin = iLogin;
            _ibitacora = Ibitacora;
        }
        [Route("")]
        //[Route("~/")]
        [Route("index")]
        public IActionResult Index()
        {
            return View();
        }
        //Autenticación del usuario

        
        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> IndexAsync([Bind("correoUsuario,passUsuario")] LoginObj loginObj)
        {
            
            var account = _iLogin.ObtenerUsuarioByID(loginObj);
            if (account != null)
            {
                if (account.olvidarUsuario == "No")
                {
                    #region AUTENTICACTION
                    var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, account.nombreUsuario),
                      new Claim(ClaimTypes.MobilePhone, account.idUsuario.ToString()),
                     new Claim(ClaimTypes.Role, account.idRolUsuario.ToString()),
                    new Claim("Correo", account.correoUsuario),
                     new Claim("id", account.idUsuario.ToString()),
                };
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                    #endregion
                    HttpContext.Session.SetString("Correo", account.correoUsuario.ToString());
                    HttpContext.Session.SetString("idUsuario", account.idUsuario.ToString());
                    _ibitacora.RegistroIngresoSistema(account);
                    return Redirect("~/Paciente/Index");
                }
                else
                {
                    HttpContext.Session.SetString("idUsuario", loginObj.idUsuario.ToString());
                    HttpContext.Session.SetString("Correo", loginObj.correoUsuario.ToString());
                    return Redirect("~/Usuario/Change");
                }
            }
            else
            {
                var accountForget = _iLogin.ObtenerCorreoUsuarioId(loginObj);
                if (accountForget != null)
                {
                    int sumarIntento = accountForget.intentosUsuario + 1;        

               _iLogin.ActualizarIntento(accountForget.correoUsuario, sumarIntento);

                if (sumarIntento >= 3)
                {
                     _iLogin.ActualizarCambiarPassBloqueado(loginObj.correoUsuario);
                    ViewBag.msg = "Usuario bloqueado, excedió la cantidad de intentos.";
                }
                else {
                    ViewBag.msg = "Error, las credenciales no son correctas";
                    return View("Index");

                }
                  }

                return View("Index");
            }
        }
        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            //HttpContext.Session.Remove("idRol");
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion
            return Redirect("~/Home/Index");
        }
    }
}

Ui/Controllers/PacienteController.cs
using Microsoft.AspNetCore.Mvc;

using Entities;
using Repository;
using X.PagedList;
using ClosedXML.Excel;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace Ui.Controllers
{

    [Authorize]
    public class PacienteController : Controller
    {
        private readonly IPaciente _Paciente;
        

        public PacienteController(IPaciente paciente)
        {
            _Paciente = paciente;
        }

        // GET: Administrar Paciente/Crear
        public IActionResult Create()
        {
            return View();
        }

        // POST: Administrar Paciente/Crear

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("idPaciente, nombrePaciente, apellido1Paciente, apellido2Paciente, idHistorialClinicoPaciente, fechaNacimientoPaciente, telefonoPaciente, direccionPaciente, generoPaciente, correoPaciente, idUsuario")] PacienteObjF paciente)
        {
            var IdValue = _Paciente.ObtenerPacienteId(Convert.ToInt32(paciente.idPaciente));
            if (IdValue == null)
            {

                if (ModelState.IsValid)
                {
                    _Paciente.InsertarPaciente(paciente);
                    return RedirectToAction("Index");
                }
                return View(paciente);
            }
            else {
                ViewBag.msg = "La cédula ya existe";
                return View();
           }
        }


        // GET: Administrar Paciente/Editar
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var paciente = _Paciente.ObtenerPacienteId(Convert.ToInt32(id));
            return View(paciente);
        }

        // POST: Administrar Paciente/Editar
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("nombrePaciente, apellido1Paciente, apellido2Paciente, idHistorialClinicoPaciente, fechaNacimientoPaciente, telefonoPaciente, direccionPaciente, generoPaciente, correoPaciente, idPaciente")] PacienteObj paciente)
        {
            if (id != paciente.idPaciente)
            {
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid)
            {
                try
                {

                    _Paciente.ActualizarPaciente(paciente);
                }
                catch (Exception)
                {
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paciente);
        }


        //// GET: Obtener Paciente
        //public IActionResult Index()
        //{
        //    return View(_Paciente.ObtenerPaciente());
        //}

        public IActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewData["idSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;

            var paciente = _Paciente.ObtenerPaciente();

            var pageNumber = page ?? 1; // if no page was specified in the querystring, default to the first page (1)
            var onePageOfProducts = paciente.ToPagedList(pageNumber, 25); // will only contain 25 products max because of the pageSize

            ViewBag.OnePageOfProducts = onePageOfProducts;

            if (!String.IsNullOrEmpty(searchString))
            {
                paciente = paciente.Where(s => s.nombrePaciente.Contains(searchString)
                                           || s.idPaciente.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "id_desc":
                    paciente = paciente.OrderBy(s => s.nombrePaciente);
                    break;
                case "Date":
                    paciente = paciente.OrderByDescending(s => s.idPaciente);
                    break;
            }

            int pageSize = 8;

            return View(paciente.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public IActionResult Export()
        {
            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[9] {
                                        new DataColumn("Cédula"),
                                        new DataColumn("Nombre Paciente"),
                                        new DataColumn("Primer Apellido"),
                                        new DataColumn("Segundo Apellido"),
                                        new DataColumn("Fecha Nacimiento Paciente"),
                                        new DataColumn("Número Telefónico"),
                                        new DataColumn("Dirección"),
                                        new DataColumn("Genero"),
                                        new DataColumn("Correo electrónico"),

            });

            var Paciente = _Paciente.ObtenerPaciente().ToList();

            foreach (var item in Paciente)
            {
                dt.Rows.Add(item.idPaciente, item.nombrePaciente, item.apellido1Paciente, item.apellido2Paciente, item.fechaNacimientoPaciente, item.telefonoPaciente, item.direccionPaciente, item.generoPaciente, item.correoPaciente);
            }

            using (XLWorkbook wb = new XLWorkbook())
            {
                wb.Worksheets.Add(dt);
                using (MemoryStream stream = new MemoryStream())
                {
                    wb.SaveAs(stream);
                    return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "PacienteReporte.xlsx");
                }
            }
        }


        // GET: Administrar Paciente/Eliminar
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var paciente = _Paciente.ObtenerPacienteId(Convert.ToInt32(id));

            if (paciente == null)
            {
                return RedirectToAction("Index");
            }

            return View(paciente);
        }

        // POST: Administrar Paciente/Eliminar

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _Paciente.EliminarPaciente(id);
            return RedirectToAction(nameof(Index));
        }






        public IActionResult HC(int id)
        {
            var paciente = _Paciente.ObtenerPacienteId(Convert.ToInt32(id));

            var f = new PacienteObjF();
            f.idPaciente = id;
            return RedirectToAction("Index", "HistorialClinico", paciente);


            // }

            // return View(paciente);
        }
    }
}

Ui/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConsultorioDrTorres</title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="~/assets/css/color/color-1.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/revolution/css/layers.css">
    <link rel="stylesheet" href="~/revolution/css/settings.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">
    <!--owl.carousel-->
    <link rel="stylesheet" href="~/owlcarousel/assets/owl.theme.default.min.css">
    <!--animation-->
    <link rel="stylesheet" href="~/assets/animation/animate.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/estilosOdontograma.css" />

    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet" asp-append-version="true">
    <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet" asp-append-version="true">
     <link rel="stylesheet" href="~/js/Datatables/Datatables.css" />
    <!-- Close Odontogram -->
    <!-- Function to start Odontrogram on View-->
</head>
<body>

    <header class="header.fixed-top">
        <div id="header">
            <div id="site-header">
                <div class="logo">

                </div>
                <img src="~/assets/image/LogoDark.png" alt="image" style="width:100px;height:100px;">

                <!-- //mobile menu button -->
                <div class="nav-wrap">
                    <nav id="mainnav" class="mainnav">
                        <ul class="menu">



                            <li>
                                <a onclick="location.href='@Url.Action("Index", "Home")'" title="">Inicio</a>
                            </li>
                            @if (User.IsInRole("1"))
                            {
                                <li>
                                    <a onclick="location.href='@Url.Action("Index", "Inventario")'" title="">Inventario</a>
                                </li>
                                <li>
                                    <a onclick="location.href='@Url.Action("Index", "Paciente")'" title="">Pacientes</a>
                                </li>
                                <li>
                                    <a onclick="location.href='@Url.Action("Index1", "Calendario")'" title="">Calendario</a>
                                </li>
                                @*<li>
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Odontograma" asp-action="Index">Odontograma</a>
                                    </li>*@

                            }



                            @if (User.IsInRole("2"))
                            {


                                <li>
                                    <a onclick="location.href='@Url.Action("Index1", "Calendario")'" title="">Calendario</a>
                                </li>

                            }


                            @if (User.IsInRole("1") || User.IsInRole("2"))
                            {
                                <li>
                                    <a onclick="location.href='@Url.Action("Logout", "Login")'" title="">Salir</a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a onclick="location.href='@Url.Action("Index", "Login")'" title="">Iniciar Sesión</a>
                                </li>

                            }







                        </ul>
                        <!-- /.menu -->
                    </nav>
                </div>
                <!-- /#mainnav -->
                <div class="contact">
                    <div class="top-bar-right">
                        <div class="call-us">

                            @ViewBag.username
                        </div>

                    </div>
                </div>

                <div class="btn-menu">
                    <span></span>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <main role="main" class="pb-3">


            <script src="assets/vendor/apexcharts/apexcharts.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/chart.js/chart.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/echarts/echarts.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/quill/quill.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/simple-datatables/simple-datatables.js" asp-append-version="true"></script>
            <script src="assets/vendor/tinymce/tinymce.min.js" asp-append-version="true"></script>
            <script src="assets/vendor/php-email-form/validate.js" asp-append-version="true"></script>
            <!-- Template Main JS File -->
            <script src="assets/js/main.js" asp-append-version="true"></script>





            <script type='text/javascript' src='js/odontCanvas/util/constants.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/util/settings.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/models/rect.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/models/damage.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/models/textBox.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/models/tooth.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/core/renderer.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/core/odontogramaGenerator.js' asp-append-version="true"></script>
            <script type='text/javascript' src='js/odontCanvas/core/collisionHandler.js' asp-append-version="true"></script>






            <script type='text/javascript' src="js/odontCanvas/core/engine.js" asp-append-version="true"></script>

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ConsultorioDrTorres - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!--Odontograma Script-->
    <script type="text/javascript" src="~/javascript/jquery-2.1.4.js"></script>
    <script src="~/javascript/angular.js"></script>
    <!--Jquery/Javascrip-->
    <script type="text/javascript" src="~/javascript/jquery-odontograma.js"></script>
    <!--Modulo de Angular-->
    <script src="~/javascript/app.js"></script>
    <!-- Angular Directivas-->
    <script src="~/javascript/controller.js"></script>

    <!-- Javascript -->
    <script type="text/javascript" src="~/javascript/jquery.min.js"></script>
    <script type="text/javascript" src="~/javascript/bootstrap.min.js"></script>
    <script type="text/javascript" src="~/javascript/jquery.easing.js"></script>
    <script type="text/javascript" src="~/javascript/jquery-countTo.js"></script>
    <script type="text/javascript" src="~/javascript/jquery-validate.js"></script>

    <!-- Revolution Slider -->
    <script type="text/javascript" src="~/javascript/rev-slider.js"></script>
    <!-- Load Extensions only on Local File Systems ! The following part can be removed on Server for On Demand Loading -->
    <script type="text/javascript" src="~/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/jquery.themepunch.tools.min.js"></script>
    <!-- <script type="text/javascript" src="revolution/js/slider_v1.js"></script>
    <script type="text/javascript" src="revolution/js/slider_v2.js"></script> -->
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script type="text/javascript" src="~/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <!--animation-->
    <script src="~/assets/animation/wow.min.js"></script>
    <script src="~/javascript/animation.js"></script>
    <!--owl.carousel-->
    <script src="~/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/owlcarousel/carousel.js"></script>
    <script type="text/javascript" src="~/javascript/main.js"></script>
    <script type="text/javascript" src="~/js/Datatables/Datatables.js"></script>



    <script src="assets/vendor/apexcharts/apexcharts.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/chart.js/chart.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/echarts/echarts.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/quill/quill.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/simple-datatables/simple-datatables.js" asp-append-version="true"></script>
    <script src="assets/vendor/tinymce/tinymce.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/php-email-form/validate.js" asp-append-version="true"></script>
    <!-- Template Main JS File -->
    <script src="assets/js/main.js" asp-append-version="true"></script>





    <script type='text/javascript' src='js/odontCanvas/util/constants.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/util/settings.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/rect.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/damage.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/textBox.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/tooth.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/renderer.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/odontogramaGenerator.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/collisionHandler.js' asp-append-version="true"></script>






    <script type='text/javascript' src="js/odontCanvas/core/engine.js" asp-append-version="true"></script>


    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Style", required: false)
</body>
</html>

Ui/Views/Shared/_autocompletar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AutocompleteDemo</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">AutocompleteDemo</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - AutocompleteDemo</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>