Ui/Controllers/OdontogramaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using DocumentFormat.OpenXml.Wordprocessing;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Repository;
namespace Ui.Controllers
{


    [Authorize(Roles = "1")]
    public class OdontogramaController : Controller
    {
        private readonly IOdontograma _Odontograma;
        public OdontogramaController(IOdontograma odontograma)
        {
            _Odontograma = odontograma;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewData["UserName"] = HttpContext.Session.GetString("UserName");
            ViewData["idUsuario"] = HttpContext.Session.GetString("idUsuario");
            ViewData["StringMessage"] = HttpContext.Session.GetString("stringValues");
            return View();
        }
        [HttpPost]
        public ActionResult Index(string jsonData)
        {
            if (jsonData == "[]")
            {
                return Json("Error, seleccione alguna pieza dental");
            }
            else
            {
                var idUsaurio = HttpContext.Session.GetString("idUsuario");
                _Odontograma.InsertarOdontograma(jsonData, idUsaurio);
                return Json(new { redirectToUrl = Url.Action("Index", "Paciente") });
            }
        }
    }
}

Ui/Views/Odontograma/Index.cshtml
@model Entities.OdontogramaObj
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="description">
    <meta content="" name="keywords">
    <!-- Favicons -->
    <link href="assets/img/favicon.png" rel="icon">
    <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Odontogram -->
    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <!-- Function to start Odontrogram on View-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Vendor CSS Files -->
    <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/quill/quill.snow.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/quill/quill.bubble.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet" asp-append-version="true" >
    <link href="assets/vendor/simple-datatables/style.css" rel="stylesheet" asp-append-version="true" >
    <!-- Close Odontogram -->
    <!-- Function to start Odontrogram on View-->
  
    <script type='text/javascript' src='js/odontCanvas/util/constants.js' asp-append-version="true" ></script>
    <script type='text/javascript' src='js/odontCanvas/util/settings.js' asp-append-version="true" ></script>
    <script type='text/javascript' src='js/odontCanvas/models/rect.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/damage.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/textBox.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/tooth.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/renderer.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/odontogramaGenerator.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/collisionHandler.js' asp-append-version="true"></script>

    <script type='text/javascript' src="js/odontCanvas/core/engine.js" asp-append-version="true"></script>

</head>
<body oncontextmenu="return true;">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-2 col-md-4 d-flex flex-column align-items-center justify-content-center">
                <div class="e-panel card">
                    <div class="card-body">
                        <br />
                        <h4 class="mr-4"><span>Crear Odontograma</span><small class="px-1"></small></h4>
                        <canvas id="canvas" width="1000" height="420"></canvas>
                 
                        <script>

        var canvas = document.getElementById('canvas');
        var engine = new Engine();
        var tooth, damage, surface, note;
        engine.setCanvas(canvas);
        console.log(engine);
        engine.init();
        canvas.addEventListener('mousedown', function (event) {
            engine.onMouseClick(event);
        }, false);
        canvas.addEventListener('mousemove', function (event) {
            engine.onMouseMove(event);
        }, false);
        window.addEventListener('keydown', function (event) {
            engine.onButtonClick(event);
        }, false);
        engine.toggleObserverState(true);

        observer = function (id) {
            var tooth = id.toString().substring(0, 2);
            var surface = id.toString().length > 2 ? id.toString().substring(3, 4) : 0;
            //Definir el daño por medio del cambio de la selección del procedimiento

            var damage = document.getElementById('txtresults').value;
            var note = 'hola'

            var carga = tooth + "," + damage + "," + surface + "," + note;

            engine.setDataSource(carga);

            // Create method to get values inside Odontogram

            var lista = engine.getData();
            const json = JSON.stringify(lista);

                $('#agregar').click(function () {
            $.ajax({
                type: 'POST',
                url: '/Odontograma/Index',
                data: {
                    jsonData: json
                },
                dataType: 'json',

                success: function (response) {
                    window.location.href = response.redirectToUrl;
                }
            });

            });
        };

             engine.setObserver(observer);



                            toothView = $(function () {
                                $("#verDientes").click(function () {
                                    var viewT = "Visualizar";
                                    var stringValues = $("#stringValue").val();
                                    var as = stringValues;
                                    console.log(as);

                                    $("#valuesOdonto").val(viewT, 0);
                                    engine.setDataSource(as);
                                    engine.setObserver(toothView);
                                    engine.onButtonClick(toothView);
                                })
                            });


                        </script>
                        <div class="container">
                            <div class="row justify-content-center">
                                <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">
                                    <div class="d-flex justify-content-center py-4">
                                        <form method="post" asp-controller="Odontograma" asp-action="login" class="row g-3 needs-validation" novalidate>
                                            <input type="text" readonly="readonly" id="txtresults" hidden />
                                            <input type="text" readonly="readonly" id="valuesOdonto" hidden />
                                            <input type="text" readonly="readonly" value=@ViewData["StringMessage"] id="stringValue" hidden />

                                            <div class="col-12">
                                                <label asp-for="procedimientoDiente" class="control-label">Procedimiento</label>
                                                <select asp-for="procedimientoDiente" id="pSelected" class="form-select" aria-label="Default select example">
                                                    <option selected>Seleccione una opción...</option>
                                                    <option value="1">Caries</option>
                                                    <option value="2">Restauración</option>
                                                    <option value="3">Restauración desajustada</option>
                                                    <option value="4">Pieza ausente</option>
                                                    <option value="5">Extracción</option>
                                                </select>
                                                <span asp-validation-for="procedimientoDiente" class="text-danger"></span>
                                            </div>
                                            <div class="col-12">
                                                <label class="control-label">Paciente</label>
                                                <input type="text" readonly="readonly" value=@ViewData["UserName"] id="Username" class="form-control" />
                                            </div>
                                            <div class="text-center">
                                                <input type="button" value="Guardar" id="agregar" class="btn btn-primary" />
                                                <input type="button" value="Cancelar" name="volver" class="btn btn-secondary" onclick="history.back()" />
                                            </div>
                                            <div class="text-center">
                                                <input type="button" value="Visualizar" id="verDientes" class="btn btn-primary" />
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
    <!-- Odontogram -->
    <!-- Vendor JS Files -->
    <script src="assets/vendor/apexcharts/apexcharts.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/chart.js/chart.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/echarts/echarts.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/quill/quill.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/simple-datatables/simple-datatables.js" asp-append-version="true"></script>
    <script src="assets/vendor/tinymce/tinymce.min.js" asp-append-version="true"></script>
    <script src="assets/vendor/php-email-form/validate.js" asp-append-version="true"></script>
    <!-- Template Main JS File -->
    <script src="assets/js/main.js" asp-append-version="true"></script>





    <script type='text/javascript' src='js/odontCanvas/util/constants.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/util/settings.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/rect.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/damage.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/textBox.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/models/tooth.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/renderer.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/odontogramaGenerator.js' asp-append-version="true"></script>
    <script type='text/javascript' src='js/odontCanvas/core/collisionHandler.js' asp-append-version="true"></script>






    <script type='text/javascript' src="js/odontCanvas/core/engine.js" asp-append-version="true"></script>




    <!-- Close Odontogram -->
    <!-- Ajax function will get the value from dropdown menu to change damage-->
    <script>



        $(function () {
            $("#pSelected").change(function(){
                const dropdownProcedimiento = $("#pSelected option:selected").val();
                $("#txtresults").val(dropdownProcedimiento, 0);
            })

       
        // carga según la necesidad de crear o editar Odonto

})


</script>
</body>
</html>